config/routes.rb
Tr::Application.routes.draw do
  resources :books

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :storage, StorageUploader
  mount_uploader :cover, CoverUploader

  validates :storage, presence: true

  before_save :set_book_info

  acts_as_taggable

  def book_name
    storage.path.split("/").last.gsub(".pdf","").gsub(/[_|.]/, " ")
  end

  def save_upload_file
    if self.save
      self.cover = ParesPdf.new(self.storage.current_path).get_cover
      self.save
    else
      false
    end
  end

  protected
    def set_book_info
      self.name ||= book_name
    end
end

app/models/pares_pdf.rb
class ParesPdf
  include CarrierWave::RMagick

  def initialize(pdf_url)
    @pdf_url = pdf_url
    @file_tmp = "#{Rails.root}/tmp/pdf_pares"
  end

  def get_cover
    image_path = File.join(@file_tmp, @pdf_url.split("/").last.sub(/.pdf/, "_1.png"))
    Docsplit.extract_images(@pdf_url, pages: "1", format: [:png], output: @file_tmp)
    File.open image_path
  ensure
    File.delete image_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @title = "book list"
    @books = Book.all
  end

  def new

  end

  def edit
    @book = Book.find(params[:id])
  end

  def show

  end

  def create
    @book = Book.new
    @book.storage = params[:storage]
    respond_to do |format|
      if @book.save_upload_file
        format.json {render json: @book, status: 200}
      else
        format.json {render json: @book.errors[:storage][0], status: 406}
      end
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.remove_storage!
    book.destroy
    render text: "success"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_book.html.erb
<div id="book_<%= book.id%>" class="book">
  <div class="book_name">
    <h4><%= book.name%></h4>
  </div>
  <%= link_to image_tag(book.cover.medium.url), book_path(book), class: "book_img"%>
  <div class="book_info">
    <p class="text-right ">
      <%= link_to "", edit_book_path(book), class: "glyphicon glyphicon-cog book_edit"%>
    </p>
  </div>
</div>

app/views/books/edit.html.erb
<div class="edit_book">
  <%= simple_form_for @book do |f|%>
    <%= f.input :name%>
  <%end%>
  <%= image_tag @book.cover.medium.url%>
</div>

app/views/books/index.html.erb
<% content_for :title do%>
  book_list
<%end%>
<div class="book_list">
  <% @books.in_groups(4).each do |group|%>
    <div class="col_strip">
      <% group.each do |book|%>
        <%if book %>
          <%= render partial: "book", locals: {book: book}%>
        <% end %>
      <%end%>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/books/new.html.erb
<div class="book_form">
  <%= form_tag "/books", id: "book_dropzone", class: "dropzone" do %>
  <% end %>
</div>

app/views/common/_bast_book.html.erb
<div class="bast_book">
  <span>Bast book</span>
</div>

app/views/common/_nearly_book.html.erb
<div class="nearly_book">
  <span>Nearly book</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title || "tr"%></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="banner">
      <div class="header">
        logo
      </div>
    </div>
    <div class="main">

<!--       <div class="path">
        <span>Path</span>
      </div> -->

      <div class="contenter">
        <%= yield %>
      </div>
    </div>
    <div class="footer">
      <div class="footer_wrap">
        Copyright
      </div>
    </div>
  </body>
</html>